#!/usr/bin/env python

import sys


def parse(line):
    try:
        path, num_bytes, num_microseconds = line.strip().rsplit(' ', 2)
    except:
        print 'LINE', repr(line)
        raise
    return path, int(num_bytes), int(num_microseconds) / 1000.0


line = next(sys.stdin, None)
if line:
    path, num_bytes, milliseconds = parse(line)
    last_path = path
    bytes_sum = num_bytes
    milliseconds_sum = milliseconds
    hits_sum = 1
else:
    sys.exit()

for line in sys.stdin:
    path, num_bytes, milliseconds = parse(line)
    if path != last_path:
        print '%s %d %d %d' % (last_path, bytes_sum, milliseconds_sum, hits_sum)
        bytes_sum = 0
        milliseconds_sum = 0
        hits_sum = 0
        last_path = path
    bytes_sum += num_bytes
    milliseconds_sum += milliseconds
    hits_sum += 1

print '%s %d %d %d' % (last_path, bytes_sum, milliseconds_sum, hits_sum)
